### ISSUE TITLE
Set-B1Subnet query

### ISSUE THREAD

**Issue by timrojaz** [TehMuffinMoo/ibPS#118]
Has anything changed that would affect the Set-B1Subnet cmdlet?
we are now getting the below with set-b1subnet. I'm trying to identify when we last used this cmdlet and if there have been any changes since.

`Invoke-RestMethod : {"error":[{"message":"The field echo_client_id cannot be set."}]}
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\ibPS\Functions\BloxOneDDI\Private\Query-CSP.ps1:96 char:23
             $Result = Invoke-RestMethod @splat -Body $Data
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
     FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by TehMuffinMoo** [comment]
Yeah it's part of the release on 22/03/24;
https://docs.infoblox.com/space/BloxOneInfrastructure/332366018/BloxOne+Release+Notes

They've added 'echo_client_id' property to the API results under `dhcp_config` and I need to have it strip this out during updates as it's a read-only field.

I'll push a bug release fix

**Comment by timrojaz** [comment]
yeah, ive just got it working with the 

$BloxSubnetPatch.dhcp_config += $BloxSubnet.dhcp_config | Select-Object * -ExcludeProperty abandoned_reclaim_time,abandoned_reclaim_time_v6,echo_client_id

**Comment by timrojaz** [comment]
Thanks, downloaded the issue_118 code and tested working. TY!

**Comment by TehMuffinMoo** [comment]
Published formal bug release;

https://github.com/TehMuffinMoo/ibPS/releases/tag/v1.9.4.1
