### ISSUE TITLE
New-B1Service cmdlet error

### ISSUE THREAD

**Issue by timrojaz** [TehMuffinMoo/ibPS#123]
Getting an error when running new-b1service

"New-B1Service -Type ntp -Name "ntp_name" -B1Host 'b1hostname' -Strict"

Invoke-RestMethod : {"error":[{"message":"HTTP interceptor error: pool_id cannot be empty"}]}
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\ibPS\Functions\BloxOne\Private\Query-CSP.ps1:90 char:27
+                 $Result = Invoke-RestMethod @splat -Body $Data
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Error. No results from API.

**Comment by TehMuffinMoo** [comment]
[v1.9.4.2 Released](https://github.com/TehMuffinMoo/ibPS/releases/tag/v1.9.4.2)

**Comment by TehMuffinMoo** [comment]
Also added this to dev for next release: https://github.com/TehMuffinMoo/ibPS/commit/991f86b9254dd4ffc0b041de6e9c3ed7abe44b05

Seems I also left an old `Write-Host` message in Get-B1Service which will print out the URI for the API call. This shouldn't cause any problems other than screen clutter, but it'll be fixed on next push anyway.

**Comment by TehMuffinMoo** [comment]
[v1.9.4.3 Released](https://github.com/TehMuffinMoo/ibPS/releases/tag/v1.9.4.3)

Includes the minor bug fix mentioned above for the random write-host debug message which was leftover.
