### ISSUE TITLE
Feature Request - VMware Deployments to hosts

### ISSUE THREAD

**Issue by timrojaz** [TehMuffinMoo/ibPS#148]
At present the company I work for are cheap, and are wanting to get rid of vsan and move away from shared datastores in a cluster.

The deploy-b1appliance requires you specify a cluster to deploy, but with no shared datastores this wont work.
What are the chances of you wanting to implement the ability to deploy direct to a host\datastore as well as cluster\datastore?

**Comment by timrojaz** [comment]
This would be a vmware type fyi

**Comment by TehMuffinMoo** [comment]
Hey mate,

Aye, super easy addition. I've added `-VMHost` as an option when using `Deploy-B1Appliance` for VMware deployments.

This will work both in two ways;

1) If the cluster is specified, it will use that particular host host from the selected cluster. If not defined, it just falls back to the old behaviour of picking the first 'Connected' host.
2) If the cluster is not specified, it will just attempt to find & use the selected host regardless of it is part of a cluster or not.

See Commit: https://github.com/TehMuffinMoo/ibPS/commit/bb83739b05f8ead2a390e74e926cd689ceabca71

**Comment by TehMuffinMoo** [comment]
Fixed in version > [1.9.8.0](https://ibps.readthedocs.io/en/latest/Change%20Log/#1980)
