### ISSUE TITLE
BootStrap export error - All other exports work fine 

### ISSUE THREAD

**Issue by timrojaz** [TehMuffinMoo/ibPS#164]
Using dev branch to export we are getting an error on one line of code, which was working on friday. 
I've isolated it to the bootstrap export:

PS C:\Users\awx> Start-B1Export -Name test_bootstrap -Description "BloxOne Daily Scheduled Backup BOOTSTRAP" -Bootstrap
Invoke-RestMethod : {"error":[{"message":"no datatypes provided; datatypes required for 
export"}]}
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ibPS\Functions\BloxOne\Private\Invoke-CSP
.ps1:122 char:27
+                 $Result = Invoke-RestMethod @splat -Body $Data
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [In 
   voke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.Invo 
   keRestMethodCommand
Error. No results from API.
Data Export failed to initialise.

**Comment by TehMuffinMoo** [comment]
Fixed bug with https://github.com/TehMuffinMoo/ibPS/commit/f90b881b4fd45cbff53a417f19f9886c4024aa07
