### ISSUE TITLE
New HA Group cmdlet

### ISSUE THREAD

**Issue by timrojaz** [TehMuffinMoo/ibPS#24]
Hi,

Would it be possible to have a SET-b1HAGROUP module.

It would be good if we can edit existing ha groups without having to remove and create a new group to alter the HA configuration.

**Comment by TehMuffinMoo** [comment]
Hey,

Yeah I can add a new cmdlet for Set-B1HAGroup. I assume this would cover most of the required usecases;

Update Comment/Description
Update HA Mode (AA/AP/AAP)
Update DHCP Services (Host A/B)
Update tags

Is there anything else to cover?

If you need to do anything urgently in the interim you can do this with the generic wrapper too, by querying the object; modifying it and then submitting it back.

Example of updating a comment for a HA Group;
```
$HAGroup = Get-B1Object -Product 'BloxOne DDI' -App Ipamsvc -Endpoint /dhcp/ha_group -Filters @('name=="ha-group-name"')
$HAGroup.comment = "Updated comment"
$HAGroup | Set-B1Object
```

**Comment by timrojaz** [comment]
Yeah that would cover the use cases.

Got the need to update 650 HA groups to active\passive unfortunately. 😄

**Comment by TehMuffinMoo** [comment]
Implemented;

**Pull Request**
https://github.com/TehMuffinMoo/ibPS/pull/25

**Gallery Publish**
https://github.com/TehMuffinMoo/ibPS/actions/runs/7782835912/job/21220067622

**Gallery Package - v1.9.2**
https://www.powershellgallery.com/packages/ibPS/1.9.2
